linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - prealloc
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  concurrency: 4
  timeout: 30s
  issues-exit-code: 2
  tests: false
  build-tags:
    - cliche_mocks
